### PR TITLE
ADD odoomrp-wip #1352 changes

### PR DESCRIPTION
**Pull request by rubencabrera**
Another option has been added via a PR in odoomrp-wip, and it's been suggested to go on with that in your PR in purchase-workflow. This option allows to create a PO from each SO, not grouping procurements for different sales orders.

I had to add the changes manually because merging deleted your last commits, but all credit goes to @drl9319 

Please let me know if I screwed anything, I'll be glad to contribute and make this merge possible (this added option is a big need of a client). 

Thanks!

### CODE REVIEW

**Comment by carlosap92** [comment]
+1

**Comment by jesuspablo** [comment]
+1 
Good point.

**Comment by tafaRU** [comment]
@rubencabrera, thanks a lot for your PR!
Please avoid changes that involve header file as they already follow the OCA guidelines, see https://github.com/OCA/maintainer-tools/blob/master/template/module/models/__init__.py as reference.
Please also add https://github.com/odoomrp/odoomrp-wip/pull/1352/commits/2b2f2c26fb84249338b36f74838792eeb7be7ebc

**Comment by rubencabrera** [comment]
Oops, sorry! I thought I was using the right header. I'll change it back and add the test.

**Comment by rubencabrera** [comment]
Is there anything else to fix?

**Comment by tafaRU** [comment]
Thanks a lot, @rubencabrera! Just merged your PR.

**Pull request merged**
